server.port=9000
spring.application.name=game-backend-marketplace
spring.datasource.url=jdbc:mysql://localhost:3306/game_marketplace
spring.datasource.username=Your_USERNAME
spring.datasource.password=YOUR_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.web.resources.static-locations=file:uploads/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Mail Configuration
